#!/usr/bin/env php
<?php

require_once __DIR__.'/prophpKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new prophpKernel('dev', true);

$application = new Application($kernel);
$application->run();
