#!/usr/bin/env php
<?php

require_once __DIR__.'/bookezpKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new bookezpKernel('dev', true);

$application = new Application($kernel);
$application->run();
